language: java
install: source /dev/stdin <<< "$(curl -sL https://ssd.mathworks.com/supportfiles/matlab-runner/install)"
script: matlab-runner --disableAutoOutfiles "ft_test run test_bug46 returnerror final"
